/* ===========================================================
   StressTest My Plan — knowledge base
   The "engine" reads from this file. Each driving force carries the
   reusable planning content (why it matters, triggers, warning signs,
   prevention, opportunity, and a consequence chain) that lets the app
   generate specific, non-generic output from a user's situation.
   Swap this for / augment with a real LLM later via the generate() seam.
   =========================================================== */
window.STKB = (function () {

  /* likelihood / severity / control are defaults the user can override */
  const F = {
    revenue_delay: {
      name: 'Revenue delay / slow cash',
      category: 'Financial',
      keywords: ['revenue','cash','income','money','slow','sales','pay','client','funding','runway','profit'],
      domains: ['business','clinical','financial','career'],
      why: 'Fixed costs continue whether or not income arrives on schedule. A gap between expenses and revenue is the single most common reason new ventures stall.',
      affected: ['Owner','Staff','Vendors','Growth plans'],
      triggers: ['Ramp-up slower than projected','Delayed client payments or payer reimbursement','One-time setup costs land before income does'],
      warning: ['Cash reserve trending down week over week','Covering operating costs from personal funds','Invoices or claims aging past their terms'],
      prevention: ['Set a minimum cash-reserve threshold and review it weekly','Model a 3–6 month runway before committing to fixed costs','Line up a bridge-income or credit option before you need it'],
      mitigation: ['Cut or defer non-essential fixed expenses','Prioritize the fastest-paying revenue lines','Renegotiate payment terms with vendors'],
      opportunity: 'Early cash discipline forces a leaner, more scalable model that holds up under pressure later.',
      chain: { immediate: 'Cash pressure', second: 'Debt risk or deferred investment', third: 'Reactive, short-term decisions that compound' },
      likelihood: 'medium', severity: 'high', control: 'medium'
    },
    cost_overrun: {
      name: 'Cost overrun / fixed-expense creep',
      category: 'Financial',
      keywords: ['cost','expense','budget','overrun','spend','overhead','rent','lease'],
      domains: ['business','clinical','financial','team'],
      why: 'Commitments made early (space, tools, headcount) become hard to reverse and quietly raise the revenue you must hit just to break even.',
      affected: ['Owner','Budget','Runway'],
      triggers: ['Signing fixed commitments before demand is proven','Scope or feature creep','Underestimating setup and compliance costs'],
      warning: ['Break-even keeps moving further out','Monthly burn higher than the plan','“Small” recurring charges adding up'],
      prevention: ['Keep fixed costs variable as long as possible (month-to-month, contractors)','Track burn vs. plan monthly','Require a payback rationale before any new recurring expense'],
      mitigation: ['Audit subscriptions and renegotiate or cancel','Convert fixed costs to variable where possible','Pause discretionary spend until revenue stabilizes'],
      opportunity: 'A lean cost base becomes a durable advantage when competitors are over-extended.',
      chain: { immediate: 'Higher burn rate', second: 'Shorter runway', third: 'Forced cuts at the worst possible time' },
      likelihood: 'medium', severity: 'medium', control: 'high'
    },
    client_concentration: {
      name: 'Over-dependence on one client / payer / platform',
      category: 'Hidden dependency',
      keywords: ['client','customer','platform','payer','one','single','depend','concentration','channel'],
      domains: ['business','clinical','career','technology'],
      why: 'When most of your income or distribution runs through one relationship, a decision you do not control can remove a large share of it overnight.',
      affected: ['Revenue','Pipeline','Negotiating leverage'],
      triggers: ['One client/payer/platform is a majority of revenue','Policy or pricing change by that party','Relationship or contact-person change'],
      warning: ['A single account is >30–40% of revenue','Terms shifting in their favor','Slower responses or renegotiation signals'],
      prevention: ['Build 3–5 independent channels or referral sources','Cap any single account as a share of revenue','Document the relationship beyond one contact person'],
      mitigation: ['Accelerate diversification while the relationship is intact','Negotiate notice periods and transition terms','Convert goodwill into referrals to new sources'],
      opportunity: 'Diversifying early makes the whole operation more valuable and easier to sell or scale.',
      chain: { immediate: 'Fragile pipeline', second: 'Sudden volume drop if the relationship changes', third: 'Revenue instability and weak negotiating position' },
      likelihood: 'medium', severity: 'high', control: 'high'
    },
    market_shift: {
      name: 'Market or demand shift',
      category: 'Market changes',
      keywords: ['market','demand','customers','trend','economy','recession','shift','need'],
      domains: ['business','financial','career','technology'],
      why: 'The assumption that today’s demand continues is the one most quietly relied on. Conditions move whether or not the plan accounts for it.',
      affected: ['Revenue','Positioning','Hiring plans'],
      triggers: ['Economic downturn or budget tightening among buyers','Changing customer preferences','A category becoming commoditized'],
      warning: ['Longer sales cycles','More price objections','Win rates slipping vs. the same quarter last year'],
      prevention: ['Track 2–3 leading demand indicators, not just revenue','Keep one foot in an adjacent segment','Stress-test the plan against a 20–30% demand drop'],
      mitigation: ['Reposition toward the most resilient segment','Adjust pricing or packaging','Shift spend to the highest-return channel'],
      opportunity: 'Downturns reshuffle the field — a prepared operator gains share while others retreat.',
      chain: { immediate: 'Softer demand', second: 'Margin and morale pressure', third: 'Strategic drift if the model is not adjusted' },
      likelihood: 'medium', severity: 'medium', control: 'low'
    },
    new_tech: {
      name: 'New technology / disruption',
      category: 'New technology',
      keywords: ['technology','ai','automation','software','tool','tech','disrupt','digital'],
      domains: ['business','career','technology','clinical'],
      why: 'New tools can change cost structures and customer expectations faster than plans built on the old way can adapt.',
      affected: ['Workflow','Pricing','Skills','Differentiation'],
      triggers: ['A capable lower-cost alternative emerges','Customer expectations reset by a new standard','Key skills becoming automatable'],
      warning: ['Customers asking why a task still costs what it does','Competitors shipping faster','Manual work that a tool now does cheaply'],
      prevention: ['Reserve time to evaluate one new tool per quarter','Compete on judgment and relationships, not just tasks','Keep skills current in the moving parts of your field'],
      mitigation: ['Adopt the tool and reprice around higher-value work','Partner rather than rebuild','Move up the value chain'],
      opportunity: 'Adopting early turns a threat into a margin and speed advantage.',
      chain: { immediate: 'Capability or price gap appears', second: 'Customers compare unfavorably', third: 'Erosion of differentiation and pricing power' },
      likelihood: 'medium', severity: 'medium', control: 'medium'
    },
    regulatory: {
      name: 'Regulatory / legal / compliance change',
      category: 'Regulatory or legal',
      keywords: ['regulation','legal','compliance','law','license','policy','rule','hipaa','privacy','audit'],
      domains: ['business','clinical','legal','financial','team'],
      why: 'Rules set the boundaries you operate inside. A change — or a gap in following an existing one — can halt operations or create liability regardless of intent.',
      affected: ['Operations','Liability','Reputation'],
      triggers: ['New or updated regulation in your field','An audit, complaint, or inquiry','Operating ahead of a license, filing, or consent'],
      warning: ['Unsure whether a current practice is compliant','Paperwork or filings slipping','Industry peers receiving notices'],
      prevention: ['Keep a short compliance checklist and review it quarterly','Build a relationship with a qualified attorney/advisor before you need one','Document consent, decisions, and policies as you go'],
      mitigation: ['Get a professional read on the specific exposure','Correct and document promptly','Notify affected parties where required'],
      opportunity: 'Strong compliance becomes a trust signal that wins cautious customers and partners.',
      chain: { immediate: 'Compliance gap or new requirement', second: 'Remediation cost and operational pause', third: 'Liability, penalties, or reputational damage' },
      likelihood: 'low', severity: 'high', control: 'medium'
    },
    credentialing_payer: {
      name: 'Credentialing / payer / reimbursement problems',
      category: 'Regulatory or legal',
      keywords: ['credential','payer','insurance','reimbursement','billing','claim','panel','medicare','medicaid'],
      domains: ['clinical','financial'],
      why: 'In a practice, getting paid depends on enrollment and clean claims. Delays here stop revenue even when the clinical work is going well.',
      affected: ['Revenue','Cash flow','Patient access'],
      triggers: ['Credentialing or enrollment delays','Claim denials or coding errors','Payer policy or fee changes'],
      warning: ['Claims aging past 30–45 days','Rising denial rate','Patients unable to use expected benefits'],
      prevention: ['Start credentialing months before launch and track each application','Verify benefits before the first visit','Reconcile claims weekly'],
      mitigation: ['Work denials promptly with a clear appeal process','Add a self-pay or sliding-scale option as a bridge','Outsource billing if denials persist'],
      opportunity: 'A tight billing workflow protects cash and frees attention for clinical care.',
      chain: { immediate: 'Delayed or denied payment', second: 'Cash-flow gap', third: 'Financial strain despite a full schedule' },
      likelihood: 'medium', severity: 'high', control: 'medium'
    },
    tech_failure: {
      name: 'System / EHR / tooling failure',
      category: 'New technology',
      keywords: ['ehr','system','booking','calendar','notification','software','outage','tool','app','scheduling'],
      domains: ['clinical','business','technology'],
      why: 'When core software quietly fails — a missed notification, a sync error — the damage shows up downstream as missed work and confused customers before you see the cause.',
      affected: ['Customers/patients','Schedule','Reputation','Revenue'],
      triggers: ['New system not notifying you of bookings','Sync or integration errors','An outage during a critical window'],
      warning: ['People say they booked but you did not know','Calendar mismatches or duplicates','Rising no-shows or confusion'],
      prevention: ['Run a daily audit of the calendar/queue against a backup','Set up a second, independent confirmation channel','Test critical workflows before going live'],
      mitigation: ['Switch to a manual backup process immediately','Communicate proactively with affected people','Escalate to vendor support with logs'],
      opportunity: 'Fixing this early can become a smoother intake and communication system than competitors offer.',
      chain: { immediate: 'Missed appointments / dropped tasks', second: 'Frustration and rework', third: 'Poor reviews and lost referrals' },
      likelihood: 'medium', severity: 'medium', control: 'high'
    },
    documentation_burden: {
      name: 'Documentation / admin backlog',
      category: 'Burnout or psychological strain',
      keywords: ['documentation','notes','admin','paperwork','charting','backlog','records'],
      domains: ['clinical','business','legal'],
      why: 'Admin work expands to fill any gap and is easy to defer — until the backlog becomes a compliance and burnout problem at the same time.',
      affected: ['Provider/owner','Compliance','Wellbeing'],
      triggers: ['Notes or records completed late','No protected time for admin','Volume rising faster than systems'],
      warning: ['Documentation consistently behind','Working evenings to catch up','Dreading the admin pile'],
      prevention: ['Block protected admin time on the calendar','Use templates to cut documentation time','Cap caseload to what you can document same-day'],
      mitigation: ['Triage the backlog oldest/highest-risk first','Delegate or automate routine admin','Temporarily reduce intake to recover'],
      opportunity: 'Streamlined documentation lifts both compliance and quality of life.',
      chain: { immediate: 'Admin backlog', second: 'Compliance exposure', third: 'Burnout and payer or audit issues' },
      likelihood: 'medium', severity: 'medium', control: 'high'
    },
    referral_dependency: {
      name: 'Fragile referral / lead pipeline',
      category: 'Hidden dependency',
      keywords: ['referral','leads','pipeline','source','word of mouth','marketing','new clients','intake'],
      domains: ['clinical','business','career'],
      why: 'A pipeline that depends on one source feels fine until that source slows — and then volume drops with little warning.',
      affected: ['New business','Revenue stability'],
      triggers: ['Most referrals from one person/source','A referrer’s situation changes','No system to generate your own demand'],
      warning: ['New inquiries down month over month','One source is most of your intake','No active outreach happening'],
      prevention: ['Build 3–5 referral channels deliberately','Make it easy and rewarding to refer you','Track where each new contact comes from'],
      mitigation: ['Re-engage past clients and referrers','Add one direct-demand channel','Strengthen the strongest existing relationships'],
      opportunity: 'A diversified pipeline is more stable and far more valuable.',
      chain: { immediate: 'Thin pipeline', second: 'Volume drop if a source slows', third: 'Revenue instability and reactive marketing' },
      likelihood: 'medium', severity: 'medium', control: 'high'
    },
    no_show: {
      name: 'No-shows / cancellations',
      category: 'Timing issues',
      keywords: ['no-show','noshow','cancel','attendance','schedule','missed'],
      domains: ['clinical','business'],
      why: 'Unfilled slots are revenue you cannot recover and a drag on momentum, especially when capacity is your product.',
      affected: ['Revenue','Schedule utilization'],
      triggers: ['Weak reminders or confirmation','No cancellation policy','Friction in rescheduling'],
      warning: ['Rising no-show rate','Gaps in an otherwise full calendar','Last-minute cancellations clustering'],
      prevention: ['Automated reminders plus an easy reschedule path','A clear, fair cancellation policy','A short-notice waitlist to fill gaps'],
      mitigation: ['Confirm high-risk slots personally','Offer flexible reschedule options','Fill cancellations from a waitlist'],
      opportunity: 'A reliable scheduling experience improves both revenue and client trust.',
      chain: { immediate: 'Empty slots', second: 'Lost revenue and rhythm', third: 'Pressure to over-book or discount' },
      likelihood: 'medium', severity: 'low', control: 'high'
    },
    staffing: {
      name: 'Staffing / key-person dependency',
      category: 'Staffing problems',
      keywords: ['staff','employee','team','hire','turnover','quit','key person','contractor'],
      domains: ['business','clinical','team'],
      why: 'When critical knowledge or capacity lives with one person, their absence — planned or not — creates an immediate gap.',
      affected: ['Operations','Customers','Remaining team'],
      triggers: ['A key person leaves or is out','Hiring takes longer than expected','Knowledge held by only one person'],
      warning: ['Only one person can do a critical task','Signs of disengagement or overload','No documented process'],
      prevention: ['Cross-train and document critical workflows','Keep a warm bench of candidates/contractors','Watch for early disengagement signals'],
      mitigation: ['Redistribute critical tasks quickly','Bring in temporary help','Prioritize knowledge transfer'],
      opportunity: 'Documented, shared processes make the operation more resilient and scalable.',
      chain: { immediate: 'Capacity or knowledge gap', second: 'Service disruption and overload', third: 'Cascading turnover and quality drop' },
      likelihood: 'medium', severity: 'medium', control: 'high'
    },
    leadership_change: {
      name: 'Leadership / decision-maker change',
      category: 'Leadership changes',
      keywords: ['leadership','founder','partner','ceo','manager','succession','decision maker','board'],
      domains: ['team','business','family'],
      why: 'A change at the top resets priorities, relationships, and decision rights, often faster than the organization can absorb.',
      affected: ['Direction','Team','Key relationships'],
      triggers: ['A founder/partner/leader exits or shifts role','A new decision-maker arrives','A succession event'],
      warning: ['Strategy ambiguity','Relationships tied to one departing person','No documented decision rights'],
      prevention: ['Document direction and key relationships, not just decisions','Plan succession for critical roles','Spread relationships across the team'],
      mitigation: ['Clarify decision rights quickly','Stabilize key relationships','Communicate continuity to stakeholders'],
      opportunity: 'A transition is a rare opening to reset priorities and shed what no longer fits.',
      chain: { immediate: 'Direction uncertainty', second: 'Relationship and morale wobble', third: 'Strategic drift or attrition' },
      likelihood: 'low', severity: 'medium', control: 'medium'
    },
    reputation: {
      name: 'Reputation / reviews / trust risk',
      category: 'Reputation risk',
      keywords: ['reputation','review','reviews','trust','brand','word of mouth','feedback','public','press'],
      domains: ['business','clinical','career','team','legal'],
      why: 'Trust is slow to build and quick to dent. In a connected market, a few bad experiences can travel further than many good ones.',
      affected: ['New business','Referrals','Morale'],
      triggers: ['A handful of bad experiences made public','A visible mistake or mishandled complaint','Silence in the face of criticism'],
      warning: ['Negative feedback appearing','Drop in referrals or inbound interest','Complaints not being closed out'],
      prevention: ['Make it easy for happy clients to leave reviews','Have a calm, standard response process for complaints','Close the loop on every complaint quickly'],
      mitigation: ['Respond professionally and fix the root cause','Ask satisfied clients to share their experience','Address the underlying operational issue'],
      opportunity: 'Handling a complaint visibly well can build more trust than never having one.',
      chain: { immediate: 'Negative perception', second: 'Lower trust and fewer referrals', third: 'Revenue and morale decline' },
      likelihood: 'medium', severity: 'medium', control: 'medium'
    },
    comms_failure: {
      name: 'Communication breakdown',
      category: 'Communication failures',
      keywords: ['communication','miscommunication','message','expectations','unclear','confusion','email'],
      domains: ['business','clinical','team','family','relationship'],
      why: 'Most failures that look like other problems are communication problems first — unspoken expectations, missed handoffs, assumed understanding.',
      affected: ['Clients','Team','Relationships'],
      triggers: ['Expectations never made explicit','Handoffs with no confirmation','Bad news delayed'],
      warning: ['Surprises that “everyone should have known”','Repeated clarification on the same things','People feeling out of the loop'],
      prevention: ['Confirm expectations in writing at key moments','Use simple templates for recurring messages','Share bad news early and plainly'],
      mitigation: ['Over-communicate during the rough patch','Create a single source of truth','Close loops explicitly'],
      opportunity: 'Clear communication becomes a noticeable differentiator clients remember.',
      chain: { immediate: 'Misaligned expectations', second: 'Errors, rework, and friction', third: 'Eroded trust and lost relationships' },
      likelihood: 'medium', severity: 'medium', control: 'high'
    },
    data_privacy: {
      name: 'Data / privacy / security exposure',
      category: 'Data/privacy concerns',
      keywords: ['data','privacy','security','breach','hipaa','records','confidential','cyber','password'],
      domains: ['clinical','business','technology','legal'],
      why: 'Sensitive data is a liability as much as an asset. A lapse can trigger legal, reputational, and trust consequences at once.',
      affected: ['Clients/patients','Liability','Reputation'],
      triggers: ['Weak access controls or shared passwords','Phishing or device loss','Vendor with poor security holding your data'],
      warning: ['Unsure who can access what','No backup or recovery plan','Sensitive data in unmanaged places'],
      prevention: ['Use strong unique credentials and 2-factor everywhere','Limit access to who truly needs it','Keep tested backups and vet vendor security'],
      mitigation: ['Contain access and rotate credentials','Notify affected parties per requirements','Engage a security professional'],
      opportunity: 'Strong data practices become a trust advantage in privacy-sensitive fields.',
      chain: { immediate: 'Exposure or breach', second: 'Notification, remediation, and legal duty', third: 'Liability and lasting trust damage' },
      likelihood: 'low', severity: 'high', control: 'medium'
    },
    vendor_dependency: {
      name: 'Vendor / platform dependency',
      category: 'Platform/vendor dependency',
      keywords: ['vendor','platform','supplier','saas','tool','provider','third party','integration'],
      domains: ['business','technology','clinical'],
      why: 'A vendor’s outage, price change, or shutdown becomes your problem instantly, and you control none of the timing.',
      affected: ['Operations','Costs','Continuity'],
      triggers: ['A core vendor changes pricing or terms','An outage or sunset of a key tool','Lock-in with no export path'],
      warning: ['No alternative identified for a critical tool','Data you cannot easily export','Pricing trending up'],
      prevention: ['Know your exit/export path for each critical vendor','Keep a backup option identified','Avoid deep lock-in where you can'],
      mitigation: ['Activate the backup or manual process','Negotiate or migrate deliberately','Export and protect your data'],
      opportunity: 'A clean, portable stack is cheaper to run and easier to evolve.',
      chain: { immediate: 'Vendor disruption', second: 'Operational gap or cost spike', third: 'Forced migration under pressure' },
      likelihood: 'low', severity: 'medium', control: 'medium'
    },
    supply_chain: {
      name: 'Supply chain / input disruption',
      category: 'Supply chain issues',
      keywords: ['supply','inventory','shipping','materials','stock','logistics','supplier'],
      domains: ['business'],
      why: 'When inputs you depend on are delayed or scarce, output stalls regardless of demand.',
      affected: ['Delivery','Costs','Customers'],
      triggers: ['Supplier delay or shortage','Shipping or logistics disruption','Single-source inputs'],
      warning: ['Lead times stretching','One supplier for a critical input','Inventory running thin'],
      prevention: ['Qualify a second supplier for critical inputs','Hold buffer stock for the most fragile items','Monitor lead times as a leading indicator'],
      mitigation: ['Activate the backup supplier','Communicate realistic timelines to customers','Reprioritize available inventory'],
      opportunity: 'A resilient supply base wins customers when competitors cannot deliver.',
      chain: { immediate: 'Input shortage', second: 'Delivery delays and cost spikes', third: 'Customer loss to more reliable competitors' },
      likelihood: 'low', severity: 'medium', control: 'medium'
    },
    insurance_liability: {
      name: 'Insurance / liability exposure',
      category: 'Insurance or liability exposure',
      keywords: ['insurance','liability','lawsuit','malpractice','claim','coverage','risk','sued'],
      domains: ['business','clinical','legal','financial'],
      why: 'A single uncovered event can outweigh years of progress. Gaps in coverage are invisible until the moment they matter.',
      affected: ['Finances','Continuity','Peace of mind'],
      triggers: ['A claim, incident, or complaint','Coverage gaps or lapses','Operating outside policy terms'],
      warning: ['Unsure exactly what is and isn’t covered','Policies not reviewed in over a year','New activities not added to coverage'],
      prevention: ['Review coverage against actual activities annually','Confirm gaps with a qualified broker/advisor','Document incidents and decisions'],
      mitigation: ['Notify the carrier promptly','Get professional guidance on the specific exposure','Correct the underlying risk'],
      opportunity: 'Right-sized coverage lets you take smart risks with a floor under you.',
      chain: { immediate: 'Coverage gap meets an event', second: 'Out-of-pocket cost or legal process', third: 'Financial and operational threat' },
      likelihood: 'low', severity: 'high', control: 'high'
    },
    relationship_conflict: {
      name: 'Relationship / partner conflict',
      category: 'Relationship conflict',
      keywords: ['relationship','conflict','partner','disagreement','spouse','co-founder','divorce','tension'],
      domains: ['family','relationship','business','team'],
      why: 'Unresolved conflict drains decision-making and can entangle finances, work, and family at the same time.',
      affected: ['Decision-making','Wellbeing','Shared commitments'],
      triggers: ['Misaligned expectations or values','Money or workload imbalance','Stress spilling across roles'],
      warning: ['Recurring unresolved arguments','Avoidance of important conversations','Decisions stalling'],
      prevention: ['Agree on expectations and decision rights in advance','Schedule regular honest check-ins','Separate the people from the problem'],
      mitigation: ['Bring in a neutral third party or mediator','Put agreements in writing','Address the underlying issue, not just symptoms'],
      opportunity: 'Working through conflict deliberately can strengthen a partnership for the long run.',
      chain: { immediate: 'Tension and stalled decisions', second: 'Spillover into finances or work', third: 'Lasting damage to the relationship or venture' },
      likelihood: 'medium', severity: 'medium', control: 'medium'
    },
    burnout: {
      name: 'Burnout / psychological strain',
      category: 'Burnout or psychological strain',
      keywords: ['burnout','stress','exhausted','overwhelmed','tired','mental','strain','overload','capacity'],
      domains: ['clinical','business','career','family','team','health'],
      why: 'Sustained overload quietly lowers judgment, patience, and follow-through — the very capacities every other plan depends on.',
      affected: ['Decision quality','Health','Everyone who depends on you'],
      triggers: ['Prolonged high demand with no recovery','Carrying too many roles alone','No boundaries between work and rest'],
      warning: ['Reactivity, avoidance, or dread','Sleep and health slipping','Small tasks feeling impossible'],
      prevention: ['Protect non-negotiable recovery time','Reduce the number of roles you carry alone','Watch your own early warning signs'],
      mitigation: ['Shed or delegate the heaviest load first','Ask for support sooner than feels necessary','Lower the bar temporarily to recover'],
      opportunity: 'Building sustainable pace early protects every other part of the plan.',
      chain: { immediate: 'Reduced capacity', second: 'Lower judgment and follow-through', third: 'Errors, conflict, and reactive decisions across the board' },
      likelihood: 'medium', severity: 'high', control: 'medium'
    },
    health: {
      name: 'Health issue / disruption',
      category: 'Health issues',
      keywords: ['health','illness','medical','sick','injury','diagnosis','disability','care'],
      domains: ['health','family','career','business'],
      why: 'A health change can remove time, energy, and income at once, and rarely arrives at a convenient moment.',
      affected: ['Capacity','Finances','Family'],
      triggers: ['A new diagnosis or injury','A flare-up of a known condition','Caregiving demands rising'],
      warning: ['Symptoms being pushed aside','No coverage plan if you are out','Energy reserves consistently low'],
      prevention: ['Have a “if I’m out for two weeks” coverage plan','Keep health and disability coverage current','Address early symptoms rather than deferring'],
      mitigation: ['Activate the coverage plan','Reduce commitments to essentials','Line up practical and professional support'],
      opportunity: 'Planning for absence makes the whole operation less fragile and more humane.',
      chain: { immediate: 'Lost time and energy', second: 'Income and continuity pressure', third: 'Strain across work and family' },
      likelihood: 'low', severity: 'high', control: 'low'
    },
    family_dynamics: {
      name: 'Family dynamics / caregiving',
      category: 'Family dynamics',
      keywords: ['family','caregiving','elder','parents','kids','inheritance','relocation','aging'],
      domains: ['family','health','financial'],
      why: 'Family decisions blend money, emotion, time, and history — which makes them slow to resolve and easy to avoid until forced.',
      affected: ['Relationships','Finances','Time'],
      triggers: ['A parent’s health declining','An inheritance or estate decision','Relocation or caregiving needs rising'],
      warning: ['Important conversations being avoided','Unclear roles among family members','Decisions made reactively in a crisis'],
      prevention: ['Have the hard conversations before the crisis','Clarify roles, wishes, and documents in advance','Agree how decisions and costs will be shared'],
      mitigation: ['Bring in a neutral facilitator or advisor','Focus on the shared goal, not old conflicts','Make reversible decisions first'],
      opportunity: 'Early, honest planning reduces conflict and protects relationships under stress.',
      chain: { immediate: 'Unresolved family decision', second: 'Conflict and reactive choices', third: 'Strained relationships and worse outcomes' },
      likelihood: 'medium', severity: 'medium', control: 'medium'
    },
    timing: {
      name: 'Timing / sequencing risk',
      category: 'Timing issues',
      keywords: ['timing','deadline','sequence','too early','too late','delay','launch','window'],
      domains: ['business','career','financial','clinical'],
      why: 'The right decision at the wrong time fails. Acting too early wastes resources; acting too late forecloses options.',
      affected: ['Resources','Options'],
      triggers: ['Committing before the picture is clear','Waiting until a window closes','Dependencies finishing out of order'],
      warning: ['Pressure to decide before key facts arrive','A reversible decision being treated as urgent','An irreversible one being deferred'],
      prevention: ['Separate reversible from irreversible decisions','Name the “decide by” date for each','Keep cheap options open as long as possible'],
      mitigation: ['Take the smallest reversible next step','Buy information before committing','Re-sequence dependencies'],
      opportunity: 'Good sequencing lets you move decisively when it counts and cheaply when it does not.',
      chain: { immediate: 'Mistimed decision', second: 'Wasted resources or missed window', third: 'Compounding constraints on later choices' },
      likelihood: 'medium', severity: 'medium', control: 'high'
    },
    competition: {
      name: 'Competitive threat',
      category: 'Competitive threats',
      keywords: ['competitor','competition','rival','market share','undercut','alternative'],
      domains: ['business','career'],
      why: 'Competitors move on their own schedule. A new entrant or aggressive move can reset pricing and expectations in your market.',
      affected: ['Pricing','Win rate','Positioning'],
      triggers: ['A new or better-funded entrant','A competitor cutting price or adding capability','Customers gaining easy alternatives'],
      warning: ['Losing deals you used to win','More price pressure','Customers name-checking alternatives'],
      prevention: ['Know your defensible difference and lead with it','Watch a short list of competitors','Deepen the relationships that are hardest to copy'],
      mitigation: ['Sharpen positioning around your real edge','Protect your best accounts','Compete on value, not just price'],
      opportunity: 'Competitive pressure clarifies what truly makes you different and worth choosing.',
      chain: { immediate: 'Competitive pressure', second: 'Margin and win-rate erosion', third: 'Lost share if positioning does not adapt' },
      likelihood: 'medium', severity: 'medium', control: 'medium'
    },
    physical_safety: {
      name: 'Physical safety risk',
      category: 'Physical safety',
      keywords: ['safety','danger','threat','violence','harm','security','unsafe'],
      domains: ['clinical','business','family','relationship'],
      why: 'Physical safety is foundational. Where there is real risk of harm, planning takes a back seat to protection and professional help.',
      affected: ['You','Staff','Family'],
      triggers: ['Threats or escalating conflict','Working alone in vulnerable settings','An unsafe person or environment'],
      warning: ['Escalating behavior','Feeling unsafe in a setting','Boundaries being ignored'],
      prevention: ['Set up safety protocols for vulnerable situations','Do not be alone with known risk','Know how to reach help quickly'],
      mitigation: ['Prioritize getting to safety','Involve appropriate authorities or professionals','Do not negotiate with active danger'],
      opportunity: '',
      chain: { immediate: 'Safety threat', second: 'Harm or trauma risk', third: 'Lasting physical, legal, and emotional impact' },
      likelihood: 'low', severity: 'high', control: 'low', sensitive: true
    },
    environmental: {
      name: 'Environmental / weather / location risk',
      category: 'Environmental/weather risks',
      keywords: ['weather','environment','climate','disaster','flood','fire','location','power','storm'],
      domains: ['business','family','health'],
      why: 'Events tied to place — weather, outages, disasters — can interrupt operations regardless of how well everything else is run.',
      affected: ['Continuity','Property','Safety'],
      triggers: ['Severe weather or natural events','Power or utility outages','A location-specific hazard'],
      warning: ['No continuity plan for an outage','Single physical point of failure','Seasonal risk approaching unprepared'],
      prevention: ['Keep a simple business-continuity / remote plan','Back up critical systems off-site','Carry appropriate coverage'],
      mitigation: ['Switch to the continuity plan','Protect people and critical assets first','Communicate status to those affected'],
      opportunity: 'A continuity plan turns a disruption into a non-event while others scramble.',
      chain: { immediate: 'Location disruption', second: 'Operational and property impact', third: 'Extended downtime without a continuity plan' },
      likelihood: 'low', severity: 'medium', control: 'medium'
    },
    political_policy: {
      name: 'Political / policy / funding change',
      category: 'Political or policy changes',
      keywords: ['policy','political','funding','grant','government','election','tariff','subsidy'],
      domains: ['business','clinical','financial','team'],
      why: 'Policy and funding shifts can change the rules or the money beneath a plan, often with little lead time.',
      affected: ['Funding','Demand','Compliance'],
      triggers: ['A funding or grant change','New policy affecting your sector','Shifts in public spending or rules'],
      warning: ['Heavy reliance on one funding source','Policy debates touching your field','No plan B if rules change'],
      prevention: ['Diversify funding and revenue sources','Track policy signals relevant to you','Keep flexibility to adapt the model'],
      mitigation: ['Shift toward less policy-dependent revenue','Engage with the process where you can','Adjust the model to the new rules'],
      opportunity: 'Policy shifts open funding and demand for those positioned to move quickly.',
      chain: { immediate: 'Rule or funding change', second: 'Revenue or compliance pressure', third: 'Model strain if not diversified' },
      likelihood: 'low', severity: 'medium', control: 'low'
    },
    missed_opportunity: {
      name: 'Missed opportunity / inaction cost',
      category: 'Missed opportunities',
      keywords: ['opportunity','missed','inaction','wait','hesitate','window','growth'],
      domains: ['business','career','financial','clinical'],
      why: 'Not every risk is something going wrong — some are openings that quietly close while attention is elsewhere.',
      affected: ['Growth','Positioning'],
      triggers: ['A window opening while focus is on defense','Hesitation past the point of advantage','Capacity tied up in low-value work'],
      warning: ['Repeatedly saying “not yet” to the same opening','Competitors moving on it','Regret about a past pass'],
      prevention: ['Reserve a little capacity for opportunistic moves','Name the openings you are choosing to skip','Set a “decide by” date for promising options'],
      mitigation: ['Take a small, reversible step toward the opening','Free capacity by cutting low-value work','Move before the window fully closes'],
      opportunity: 'Treating opportunity as a planned category keeps growth from being crowded out by defense.',
      chain: { immediate: 'Opening goes untaken', second: 'Competitor or circumstance takes it', third: 'Slower growth and weaker position' },
      likelihood: 'medium', severity: 'low', control: 'high'
    }
  };

  /* ---- domains: which forces are most relevant + who to involve ---- */
  const DOMAINS = {
    business:   { label: 'Business / startup', forces: ['revenue_delay','client_concentration','market_shift','competition','vendor_dependency','staffing','reputation','comms_failure','cost_overrun','timing','burnout','missed_opportunity'], help: ['Accountant / bookkeeper','Small-business mentor (e.g. SCORE)','Business attorney','Banker or lender'] },
    clinical:   { label: 'Private practice / clinical operations', forces: ['revenue_delay','credentialing_payer','tech_failure','documentation_burden','referral_dependency','reputation','regulatory','burnout','no_show','data_privacy','insurance_liability','comms_failure'], help: ['Healthcare attorney','Billing / credentialing specialist','Accountant','Malpractice carrier / broker','Peer consultation group'] },
    financial:  { label: 'Financial', forces: ['revenue_delay','cost_overrun','market_shift','timing','insurance_liability','political_policy'], help: ['Accountant / CPA','Fee-only financial planner','Credit counselor'] },
    family:     { label: 'Family', forces: ['family_dynamics','health','relationship_conflict','comms_failure','burnout','insurance_liability'], help: ['Elder-law / estate attorney','Fee-only financial planner','Family therapist','Geriatric care manager'] },
    health:     { label: 'Health', forces: ['health','burnout','family_dynamics','insurance_liability','comms_failure'], help: ['Your physician / care team','Patient advocate','Care manager','Insurer / benefits contact'] },
    career:     { label: 'Career', forces: ['revenue_delay','market_shift','new_tech','reputation','timing','burnout','missed_opportunity'], help: ['Career coach / mentor','Financial planner','Trusted peers in your field'] },
    relationship:{ label: 'Relationship', forces: ['relationship_conflict','comms_failure','burnout','family_dynamics'], help: ['Licensed therapist / counselor','Neutral mediator'] },
    legal:      { label: 'Legal / regulatory', forces: ['regulatory','insurance_liability','reputation','documentation_burden','data_privacy'], help: ['Qualified attorney in the relevant area'] },
    team:       { label: 'Team / organization', forces: ['staffing','leadership_change','comms_failure','reputation','burnout','vendor_dependency','regulatory'], help: ['HR / employment attorney','Executive coach','Operations lead'] },
    technology: { label: 'Technology', forces: ['new_tech','vendor_dependency','data_privacy','tech_failure','comms_failure','supply_chain'], help: ['Security consultant','Vendor support','Technical advisor'] },
    custom:     { label: 'Something else', forces: ['comms_failure','timing','burnout','reputation','relationship_conflict','missed_opportunity','financial' ], help: ['A trusted advisor in the relevant field'] }
  };

  /* ---- tone presets (shape narrative voice; engine stays the same) ---- */
  const TONES = {
    practical: { label: 'Practical', lead: 'Here is the plain-language read:' },
    executive: { label: 'Executive', lead: 'Executive summary:' },
    clinical:  { label: 'Clinical', lead: 'Clinical-operations view:' },
    founder:   { label: 'Founder-focused', lead: 'Founder’s read:' },
    family:    { label: 'Family-focused', lead: 'For the family conversation:' },
    detailed:  { label: 'Detailed', lead: 'A fuller walk-through:' },
    simple:    { label: 'Simple', lead: 'In short:' }
  };

  /* ---- safety: sensitive content shifts tone and surfaces real help ---- */
  const SAFETY = {
    categories: [
      { id: 'self_harm', label: 'Self-harm or suicide',
        keywords: ['suicide','suicidal','kill myself','kill himself','kill herself','end my life','self-harm','self harm','hurt myself','want to die','don\'t want to live','overdose'],
        message: 'It sounds like there may be thoughts of suicide or self-harm involved. This tool can’t help with that, but people who can are available right now.',
        resources: ['988 Suicide & Crisis Lifeline — call or text 988 (US)','Crisis Text Line — text HOME to 741741','If someone is in immediate danger, call 911 or your local emergency number'] },
      { id: 'violence', label: 'Abuse or domestic violence',
        keywords: ['domestic violence','abuse','abusive','being hit','threatened','stalking','assault','unsafe at home','afraid of him','afraid of her','afraid of them'],
        message: 'It sounds like safety and possible abuse may be involved. Please prioritize safety over planning, and consider reaching out to people trained to help.',
        resources: ['National Domestic Violence Hotline — 1-800-799-7233 (US), or text START to 88788','If you are in immediate danger, call 911 or your local emergency number','Plan around your safety first; avoid steps that could escalate an unsafe situation'] },
      { id: 'emergency', label: 'Immediate danger or medical emergency',
        keywords: ['emergency','immediate danger','right now in danger','medical emergency','can\'t breathe','chest pain','overdosing','bleeding badly'],
        message: 'This sounds like it may be an emergency. A planning tool is not the right help for something happening right now.',
        resources: ['Call 911 or your local emergency number now','Contact a nearby person who can help immediately'] }
    ]
  };

  /* ---- the worked example (loads the full flow with one tap) ---- */
  const EXAMPLE = {
    title: 'Launching a small mental health private practice',
    domain: 'clinical',
    tone: 'clinical',
    fields: {
      planningFor: 'Launching a small solo mental health private practice over the next 6 months.',
      hope: 'A steady caseload, smooth operations, and enough revenue to replace my salary within a year.',
      worry: 'Slow revenue while fixed costs run, EHR/booking problems causing missed appointments, and bad reviews early on.',
      affected: 'Me, my patients, my reputation, and my household finances.',
      timeline: '6 months',
      tried: 'Picked an EHR, started credentialing, set up a basic website.',
      avoiding: 'Deciding how long I can run at a loss before changing the plan.'
    },
    /* pre-selected forces so the example produces a rich result instantly */
    forces: ['revenue_delay','credentialing_payer','tech_failure','referral_dependency','reputation','documentation_burden','burnout','no_show']
  };

  return { forces: F, domains: DOMAINS, tones: TONES, safety: SAFETY, example: EXAMPLE };
})();
